# .github/workflows/ci-cd.yml
name: Build and Deploy Blog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.6
          bundler-cache: true

      - name: Remove bundle frozen
        run: bundle config set frozen false

      - name: Install dependencies
        run: bundle install

      - name: Test build
        run: bundle exec jekyll build

      - name: Make test script executable
        run: chmod +x ./script/test
        
      - name: Run test script
        run: ./script/test
        
      - name: Run tests
        run: ./script/test
          gem install html-proofer
          bundle exec htmlproofer ./_site --disable-external

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site